AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template is used to deploy a simple vpc that is partitioned
  in a private and public network, with a configured NAT gateway for     
  the private network and an internet gateway for the public
  network.
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Join ['', [!Ref "AWS::StackName", "-VPC"]]